# DATABASE:
#   host: localhost
#   user: karen
#   password: password
#   database: hh
#   port: 3306

# FRONTEND_URL: http://localhost

DATABASE:
  host: myhost
  user: root
  password: 061697Jfc
  database: hh
  port: 3306

FRONTEND_URL: http://localhost