name: Continuous Integration

on:
  push:
    branches:
      - personal/bugfix
  pull_request:
    branches:
      - main
      - develop
    
jobs:
  build:
    name: Jenkin test thru push
    runs-on: ubuntu-latest
    env:
      working-directory: './continuous integration/survey-form-v1'
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: Test project
      run: npm test
      working-directory: ${{env.working-directory}}
